name: ${name}
version: ${version}
main: ${main}
author: Liangbai
api-version: '1.13'
softdepend:
  - Multiverse-Core
commands:
  rh:
    description: ''
    aliases:
      - realhomehunt
      - rhh
permissions:
  rh.select:
    description: Allow player to select the residence zone.
    default: 'true'
  rh.unlimited.create:
    description: Allow player ignore the zone size limit.
    default: op
  rh.unlimited.back:
    description: Allow player to teleport to other residences.
    default: op
  rh.interact:
    description: Allow player to click the residence's door.
    default: op
  rh.break:
    description: Allow player to break blocks in residences.
    default: op
  rh.place:
    description: Allow player to place blocks in residences.
    default: op
  rh.command.help:
    description: Allow player to use the /rh help command.
    default: 'true'
  rh.command.create:
    description: Allow player to use the /rh create command.
    default: 'true'
  rh.command.back:
    description: Allow player to use the /rh back command.
    default: 'true'
  rh.command.setspawn:
    description: Allow player to use the /rh setspawn command.
    default: 'true'
  rh.command.set:
    description: Allow player to use the /rh set command.
    default: 'true'
  rh.command.remove:
    description: Allow player to use the /rh remove command.
    default: 'true'
  rh.command.administrator:
    description: Allow player to use the /rh administrator command.
    default: 'true'
  rh.command.confirm:
    description: Allow player to use the /rh confirm command.
    default: 'true'
  rh.command.reload:
    description: Allow player to use the /rh reload command.
    default: op
  rh.command.admin:
    description: Allow player to use the /rh admin command.
    default: op
  rh.command.admin.help:
    description: Allow player to use the /rh admin help command.
    default: op
  rh.command.admin.import:
    description: Allow player to use the /rh admin import command.
    default: op
  rh.reload:
    description: Allow player to reload the configuration.
    default: op